# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
    # teamr R depends
  - ./travis-tool.sh install_r_binary raster
    # teamr R imports deps
  - ./travis-tool.sh install_r_binary Rcpp RcppArmadillo rgeos rgdal mgcv plyr reshape2 ggplot2 kernlab e1071 randomForest spatial.tools caret sp mclust lubridate XML
    # teamr R suggested
  - ./travis-tool.sh install_r_binary testthat landsat foreach doSNOW gridExtra itertools
    # others
  - ./travis-tool.sh install_r_binary devtools httr

install:
  - ./travis-tool.sh install_github azvoleff/spatial.tools
  - ./travis-tool.sh install_github azvoleff/wrspathrowData
  - ./travis-tool.sh install_github azvoleff/wrspathrow
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_github hadley/httr

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
